---
- hosts: all
  become: yes
  tasks:
  - name: i want to install apache2 on ubuntu server
    apt:
     name: apache2
     state: present
    when: ansible_os_family == "Debian"

  - name: i want to start my server
    apt:
     name: apache2
     state: present
    when: ansible_os_family == "Debian"

  - name: i want to install server on Redhat hosts
    apt:
     name: httpd
     state: present
    when: ansible_os_family == "RedHat"
    



