--- 
- hosts: 172.31.47.96
  become: yes
  tasks:
  - name: i want to install webserver on ubuntu
    apt: 
      name: apache2
      state: present
    tags: myapache2

  - name: i want to install tree
    apt:
      name: treeeee
      state: present
    tags: mytree
    

  - name: i want to install wget
    apt: 
      name: wget
      state: present
    tags: myweget