---
- name: copy tomcat user file
  template: 
      src: templates/mytomcat.j2
      dest: /opt/tomcat/conf/tomcat-users.xml


- name: copy context file
  template:
      scr: templates/context.j2
      dest: /opt/tomcat/webapps/manager/META-INF/context.xml

- name: copy host context file
  template:
      scr: templates/myhostcontext.j2
      dest: /opt/tomcat/webapps/host-manager/META-INF/context.xml